name: CI/CD Workflow

on:
  - push

env:
  REPOSITORY: gcp-kms
  TERRAFORM_DIR: terraform
  TERRAFORM_VERSION: 0.12.18
  TERRAFORM_STATE_BUCKET: chatstatz-control-tfstate

jobs:
  ci_cd:
    name: CI/CD
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Install gcloud SDK
        run: |
          curl https://sdk.cloud.google.com > install.sh
          bash install.sh --disable-prompts

      - name: Activate Service Account
        run: |
          echo "$GCLOUD_AUTH" | base64 --decode > "${PWD}/gcloud.json"
          sh -c "gcloud auth activate-service-account --key-file=${PWD}/gcloud.json"
        env:
          GCLOUD_AUTH: ${{ secrets.GCP_CONTROL_DEPLOYER_SA_KEY }}

      - name: Terraform Format
        run: .github/scripts/terraform_fmt.sh

      - name: Terraform Init
        run: .github/scripts/terraform_init.sh
        env:
          SLICE: master # masquerade as 'master' for the purpose of validating changes

      - name: Terraform Validate
        run: .github/scripts/terraform_validate.sh

      - name: Terraform Plan
        run: .github/scripts/terraform_plan.sh
        env:
          SLICE: master # masquerade as 'master' for the purpose of validating changes

      - name: Terraform Apply
        if: github.ref == 'refs/heads/master'
        run: .github/scripts/terraform_apply.sh
